### ISSUE TITLE
5 December - Best practices in data analysis workflow and project management in R

### ISSUE THREAD

**Issue by lwjohnst86** [au-oc/Events#10]
Do you often forget which files are part of which project? Does it take some time to find all the files you need for an analysis and manuscript? In these session we will cover best practices on workflows and project management. An efficient, systematic, and standardized workflow is essential to being more reproducible and writing better code. It's also important for doing more rigorous science and being more open. Come to this session to learn how to set up and use an efficient, open, and reproducible workflow that will help you organise not only your code, but also your mind!

- **When**: 5 December, from 10:00-12:00
- **Where**: [Aarhus University](https://goo.gl/maps/4GX8znvPE9o) campus, AU campus, building 1264, room 310
- **Skill level**: Intermediate
- **Series**: Analysis Workflow
- **What to bring**: Since this is an interactive code along, it would be best if you bring your laptop!

*Installation instructions*:

You will need to install the appropriate programs. See the R section of the [installation instructions page](https://au-oc.github.io/content/installation). 

Please also install these packages: prodigenr, usethis, drake using the `install.packages` command.

**Comment by lwjohnst86** [comment]
Lesson content is here: https://au-oc.github.io/content/workflow-setup.html

**Comment by lwjohnst86** [comment]
Requested by a few people, here is the screen recording of the session: https://youtu.be/vAcdq7FHJZA

I forgot to start it right away, so the first 5 minutes of the session were not recorded.

**Comment by jakn09ab** [comment]
This is great! Great initiative!

 

Fra: Luke W Johnston <notifications@github.com>
Svar til: au-oc/Events <reply@reply.github.com>
Dato: onsdag den 5. december 2018 kl. 16.45
Til: au-oc/Events <Events@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: Re: [au-oc/Events] 5 December - Best practices in data analysis workflow and project management in R (#10)

 

Requested by a few people, here is the screen recording of the session: https://youtu.be/vAcdq7FHJZA

I forgot to start it right away, so the first 5 minutes of the session were not recorded.
