### ISSUE TITLE
26 October - Work with and manage your data efficiently in R

### ISSUE THREAD

**Issue by lwjohnst86** [au-oc/Events#4]
Analyzing, using, wrangling, and molding data are a core feature and focus of R, as it is a statistical programming language. Come learn the basics of working with and wrangling data (called data frames in R) in this session!

- **When**: 26 October, from 10:00-11:30
- **Where**: Aarhus University campus, building 1264, room 310
- **Skill level**: Beginner
- **Series**: Introduction To R
- **What to bring**: Since this is an interactive code along, it would be best if you bring your laptop!

*Installation instructions*:

You will need to install the appropriate programs. See the R section of the [installation instructions page](https://au-oc.github.io/content/installation).

Please also install these packages: tidyverse using the `install.packages` command.

**Comment by Qvand** [comment]
I probably won't make it to this session tomorrow, but looking forward to seeing the codes, see you next time!
/Jörg

**Comment by lwjohnst86** [comment]
Lesson content is available here: https://au-oc.github.io/content/intro-dplyr.html
