### ISSUE TITLE
19 October - Generate beautiful and insightful graphics in R

### ISSUE THREAD

**Issue by lwjohnst86** [au-oc/Events#5]
One of the main strengths of R is it's ability to create beautiful and meaningful graphs with very little code. Come to this session to learn about the "grammer of graphics" with ggplot2.

- **When**: 19 October, from 10:00-11:30
- **Where**: Aarhus University campus, building 1264, room 310
- **Skill level**: Beginner
- **Series**: Introduction To R
- **What to bring**: Since this is an interactive code along, it would be best if you bring your laptop!

*Installation instructions*:

You will need to install the appropriate programs. See the R section of the [installation instructions page](https://au-oc.github.io/content/installation). 

Please also install these packages: tidyverse using the `install.packages` command.

**Comment by johnmcgrath19** [comment]
These workshops looks great! 
By the way, we had Yan Holtz give a lecture at Aarhus Uni a few months on data viz. Yan is the curator of a few great web resources
https://www.data-to-viz.com/
https://www.r-graph-gallery.com/

You can see a video of his lecture on this Youtube channel 
https://www.youtube.com/watch?v=NLmPO7t0FjM

Here is Yan's GitHub account 
https://github.com/holtzy

Cheers
John

**Comment by lwjohnst86** [comment]
Material for the session can be found here: https://au-oc.github.io/content/intro-ggplot2.html
